[project]
name = "rav"
version = "0.1.0"
requires-python = ">=3.13,<4.0"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true

[tool.uv.workspace]
members = [
  "packages/e1c",
  "packages/e1c/packages/ext",
  "packages/e1c/packages/ext/packages/meta",
]