[project]
name = "rav"
version = "0.1.0"
requires-python = ">=3.13,<4.0"
dependencies = []

[tool.uv]
link-mode = "copy"

[tool.uv.pip]
link-mode = "copy"

[tool.uv.workspace]
members = [
    "packages/e1c",
    "packages/e1c/packages/ext",
    "packages/e1c/packages/ext/packages/meta",
]