[project]
name = "rav"
version = "0.1.0"
requires-python = ">=3.13,<4.0"
dependencies = []

[tool.uv]
link-mode = "copy"
constraint-dependencies = [
    "fastapi>=0.116.1; python_version>='3.13,<4.0'",
    "cashews>=7.4.1; python_version>='3.13,<4.0'"
]

[tool.uv.pip]
link-mode = "copy"

[tool.uv.workspace]
members = [
    "packages/e1c",
    "packages/e1c/packages/ext",
    "packages/e1c/packages/ext/packages/meta",
]