[project]
name = "rav-e1c"
version = "0.1.0"
requires-python = ">=3.13,<4.0"
dependencies = [
    "httpx>=0.28.1",
]

[build-system]
requires = ["uv_build>=0.8.7,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
link-mode = "copy"

[tool.uv.pip]
link-mode = "copy"
